name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-16.04]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install build tools
      if: matrix.os == 'macos-latest'
      run: brew install autoconf automake libtool pkg-config
    - name: bootstrap and configure
      run: ./bootstrap && ./configure --enable-debug
    - name: make
      run: make
    - name: make distcheck
      run: make VERBOSE=1 distcheck

  build_asan:
    name: Sanitizer build (ubuntu-16.04)
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: bootstrap and configure
      run: |
        ./bootstrap
        ./configure --enable-debug \
          CFLAGS="-fsanitize=address,leak" \
          LDFLAGS="-fsanitize=address,leak"
    - name: make
      run: make
    - name: make check (upnp)
      run: cd upnp && make check || (cat test-suite.log && exit 1)
    - name: make check (ixml)
      run: cd ixml && make check || (cat test-suite.log && exit 1)
